/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {

        Shop newShop = new Shop("123Shop", "new cloth Shop",100);
        System.out.println(newShop.toString());


        Review Rev1= new Review("this restaurant is perfect ", "Manar",4);
        Theater theater = new Theater("First theater");
        theater.addMovie("Frozen");
        theater.addMovie("Home alone");
        System.out.println(theater.toString());
        System.out.println(theater.AddReview(Rev1));
//        Restaurant Rest1 = new Restaurant("My restaurant", "250",4);
//        System.out.println( Rest1.toString());
//
//        Review Rev1= new Review("this restaurant is perfect ", "Manar",4);
//        Rest1.AddReview(Rev1);
//        System.out.println( Rev1.toString());
//
//        System.out.println("\n");
//        System.out.println(Rest1);
//
//        Review Rev2= new Review("it is comfortable ", "Sadan",2);
//        Rest1.AddReview(Rev2);
//        System.out.println(Rest1);
//        System.out.println("\n");
//        Review Rev3= new Review("it is comfortable ", "Elien",3);
//        Rest1.AddReview( Rev3);
//        System.out.println(Rest1);
//        System.out.println("\n");
//        Review Rev4= new Review("it is comfortable ", "Elien",10);
//        Rest1.AddReview( Rev4);
//        System.out.println(Rest1);
    }


}



