/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

<<<<<<< HEAD
import java.io.*;
=======
import java.io.File;
import java.io.FileNotFoundException;
>>>>>>> cfa86be343302a00336690aab1117062cde726fb
import java.util.ArrayList;
import java.util.Scanner;

public class
App {
    public boolean getGreeting() {
        return true;
    }

    public static void main(String[] args) {
<<<<<<< HEAD
        fileReader("app/src/main/resources/gates.js");
//        System.out.println(new App().getGreeting());
    }

    public static ArrayList<String> fileReader(String file)
    {        ArrayList<String> err = new ArrayList<>();
        try {

            // open file to read
            Scanner scanner = new Scanner(new File(file));
            int linNum =0;
            System.out.println("file opened");
            // read until end of file (EOF)
            String data = scanner.nextLine();
            while (scanner.hasNextLine()) {
                linNum++;
                System.out.println(scanner.nextLine());
                if( data.endsWith(";") || data.endsWith("}") || data.endsWith("{") || data.contains("if") || data.contains("else") ){
                    System.out.println(data);
                    err.add("Line "+linNum+" : Missing semicolon.");
                    System.out.println("Line : "+linNum+"  Missing semicolon." );
//                    System.out.println("linnum =  " +linNum);
                }

                else{
                    linNum++;
                    err.add("Line "+linNum+" : Missing semicolon.");
                    System.out.println("Line : "+linNum+"  Missing semicolon." );
                }

                data = scanner.nextLine();
=======
        ArrayList<String> ErrorMessages = fileReader();
        System.out.println("error in line");
//        for (String error:
//                ErrorMessages) {
//            System.out.println(error);
//        }
//        System.out.println(new App().getGreeting());
//        fileReader();
    }

    public static ArrayList<String> fileReader()
    {
        try {
            File file = new File("gates.js");
            Scanner myReader = new Scanner(file);
            while (myReader.hasNextLine()) {
                String data = myReader.nextLine();
                System.out.println(data);
>>>>>>> cfa86be343302a00336690aab1117062cde726fb
            }

            // close the scanner
            scanner.close();
            System.out.println("file closed");

        } catch (FileNotFoundException ex) {
            System.err.println("an error occured");
            ex.printStackTrace();
        }
<<<<<<< HEAD


        return err;
    }}


=======
        return null;
    }
}
>>>>>>> cfa86be343302a00336690aab1117062cde726fb
