/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {
    public boolean getGreeting() {
        return true;
    }

    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    }

    public void fileReader()
    {
        try {
            File file = new File("app/src/main/resources/gates.js");
            Scanner myReader = new Scanner(file);
            while (myReader.hasNextLine()) {
                String linenum = myReader.nextLine();
                System.out.println(linenum);
            }
            String newline = myReader.nextLine();
            while (newline != null)
            {
                if (!newline.endsWith(";" )|| newline.endsWith("{" )|| newline.endsWith("}")|| newline.contains("if")||newline.contains("else"))
                    System.out.println("Line " + newline + ": Missing semicolon.");
            }
            myReader.close();
        } catch (FileNotFoundException e) {
            System.err.println("An error occurred.");
            e.printStackTrace();
        }
    }
}
